name: CD

on: 
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build SASS
      run: yarn && yarn sass
    - name: Bundle
      run: mkdir ./out && mkdir ./out/anime && cp -r css fonts images js ./out/anime/ && cp index.html ./out/anime/
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        external_repository: MemboLembo/MemboLembo.github.io
        publish_dir: ./out
        publish_branch: master
        keep_files: true
